# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

$mainMod = SUPER
$terminal = alacritty
$fileManager = nautilus
$menu = rofi -show run

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu

windowrule = match:class ^(Alacritty)$, maximize = 1

monitor = LVDS-1, preferred, auto, 1

exec-once = waybar
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swaybg -i $DOTFILES/dragon.png -m fill

general {
  gaps_in = 0
  gaps_out = 0
  border_size = 0
}

decoration {
  rounding = 0
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  background_color = 0x282828
}
